"""LangGraph agent state — shared across all nodes of the pipeline."""
from __future__ import annotations

from typing import Annotated, Any, Dict, Optional

from langchain_core.messages import HumanMessage
from langgraph.graph.message import add_messages
from typing_extensions import TypedDict


class AgentState(TypedDict):
    """Shared state propagated through every node in the LangGraph pipeline.

    Fields
    ------
    messages:
        Conversation history managed by LangGraph's ``add_messages`` reducer.
        New messages are appended; existing messages with the same id are updated.
    user_id:
        The authenticated user's identifier (UUID string from the JWT).
    user_role:
        The authenticated user's role.  Must be one of: "admin", "manager",
        "employee".
    detected_domain:
        Domain routed to by the orchestrator: "hr" | "crm" | "erp" | "rag"
        | "multi".  ``None`` until the classification node runs.
    domain_confidence:
        Confidence score [0.0 – 1.0] returned by the classification step.
    tool_results:
        Structured data returned by domain-specific tool calls (SQL results,
        graph lookups, …).  Keyed by tool name.
    rag_context:
        Concatenated RAG chunks retrieved from ChromaDB, ready to be injected
        into the final prompt.
    final_response:
        Markdown-formatted French response generated by the synthesis node.
        Set to a non-None value to signal the pipeline is done.
    requires_write:
        True when the user intent implies a write / mutating operation (INSERT,
        UPDATE, DELETE).  Guards write-access controls.
    error_message:
        Human-readable error description set by any node that catches an
        exception.  The synthesis node renders it gracefully.
    iteration_count:
        Number of agent loop iterations completed so far.  Used to enforce a
        hard cap and prevent infinite loops.
    secondary_domain:
        Optional second domain identified for cross-domain (multi) queries,
        e.g. "hr" when the primary is "crm".
    requires_email:
        True when the user intent implies sending an email.  Triggers the
        email_agent_node after domain data has been gathered.
    requires_report:
        True when the user intent implies generating a formal report (rapport).
        The final_response_node will use REPORT_PROMPT instead of the default
        synthesis prompt, producing a structured Markdown report with header,
        date, executive summary and sections.
    email_result:
        Metadata about the email that was sent: recipient, subject, and
        SMTP result string.  Populated by email_agent_node.
    world_model_snapshot:
        Snapshot Neo4j du domaine détecté, injecté dans le system prompt
        des domain agents.  {} si Neo4j est indisponible.  None avant
        que world_model_node ne s'exécute.
    """

    messages: Annotated[list, add_messages]
    user_id: str
    user_role: str
    detected_domain: Optional[str]
    domain_confidence: Optional[float]
    tool_results: Optional[Dict[str, Any]]
    rag_context: Optional[str]
    final_response: Optional[str]
    requires_write: bool
    requires_email: bool
    requires_report: bool
    email_result: Optional[Dict[str, Any]]
    error_message: Optional[str]
    iteration_count: int
    secondary_domain: Optional[str]
    world_model_snapshot: Optional[Dict[str, Any]]


# ── Helpers ───────────────────────────────────────────────────────────────────

def initial_state(user_id: str, user_role: str, message: str) -> AgentState:
    """Build a fresh AgentState for the start of a new conversation turn.

    Parameters
    ----------
    user_id:
        Authenticated user identifier.
    user_role:
        Must be one of "admin", "manager", "employee".
    message:
        The raw user message that kicks off this pipeline run.

    Returns
    -------
    AgentState
        Fully initialised state with sensible zero-values.
    """
    valid_roles = {"admin", "manager", "employee"}
    if user_role not in valid_roles:
        raise ValueError(
            f"Invalid user_role '{user_role}'. Must be one of {sorted(valid_roles)}."
        )

    return AgentState(
        messages=[HumanMessage(content=message)],
        user_id=user_id,
        user_role=user_role,
        detected_domain=None,
        domain_confidence=None,
        tool_results=None,
        rag_context=None,
        final_response=None,
        requires_write=False,
        requires_email=False,
        requires_report=False,
        email_result=None,
        error_message=None,
        iteration_count=0,
        secondary_domain=None,
        world_model_snapshot=None,
    )


def is_terminal(state: AgentState) -> bool:
    """Return True when the pipeline should stop processing.

    The graph is considered terminal when:
    - A ``final_response`` has been produced, OR
    - An ``error_message`` is present (graceful error path), OR
    - The ``iteration_count`` has reached or exceeded the hard cap of 10.
    """
    if state.get("final_response") is not None:
        return True
    if state.get("error_message") is not None:
        return True
    if state.get("iteration_count", 0) >= 10:
        return True
    return False
